const fs=require('fs'),path=require('path'); const {DatabaseSync}=require('node:sqlite');
const BRANDS=['RUPIAH TOTO','OMTOGEL','DENTOTO','BINJAI','MERDEKA','MUSIM','SERVER','SITOTO','SOSMED','BANDARTO','WDBANDAR','CYBER88','KAKAKTOGEL','RAJAALADIN'];
const nowIso=()=>new Date().toISOString(); const id=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`;
class Store{
 constructor(dataDir){fs.mkdirSync(dataDir,{recursive:true});this.dataDir=dataDir;this.shotDir=path.join(dataDir,'screenshots');fs.mkdirSync(this.shotDir,{recursive:true});this.db=new DatabaseSync(path.join(dataDir,'monitor.db'));this.db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA busy_timeout=5000;');this.migrate()}
 try(sql){try{this.db.exec(sql)}catch(e){if(!/duplicate column|already exists/i.test(e.message))throw e}}
 migrate(){this.db.exec(`CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,name TEXT NOT NULL,version TEXT,online INTEGER NOT NULL DEFAULT 0,last_seen TEXT,last_error TEXT,current_job_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS scans(id TEXT PRIMARY KEY,target_date TEXT NOT NULL,status TEXT NOT NULL,device_id TEXT,total INTEGER NOT NULL DEFAULT 0,checked INTEGER NOT NULL DEFAULT 0,normal INTEGER NOT NULL DEFAULT 0,mischat INTEGER NOT NULL DEFAULT 0,errors INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,started_at TEXT,completed_at TEXT,lock_until TEXT,error TEXT);CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,scan_id TEXT NOT NULL,target_date TEXT NOT NULL,chat_id TEXT NOT NULL,fingerprint TEXT NOT NULL,user_id TEXT,agent TEXT,last_customer_text TEXT,last_customer_at TEXT,status TEXT NOT NULL,archive_url TEXT,screenshot_path TEXT,telegram_status TEXT NOT NULL DEFAULT 'NOT_SENT',telegram_error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,detail TEXT);`);
  this.try(`ALTER TABLE scans ADD COLUMN brand TEXT NOT NULL DEFAULT 'OMTOGEL'`);this.try(`ALTER TABLE scans ADD COLUMN checkpoint_chat_id TEXT`);this.try(`ALTER TABLE scans ADD COLUMN checkpoint_at TEXT`);this.try(`ALTER TABLE results ADD COLUMN brand TEXT NOT NULL DEFAULT 'OMTOGEL'`);this.try(`ALTER TABLE results ADD COLUMN scanner_version TEXT NOT NULL DEFAULT ''`);
  this.db.exec(`DELETE FROM results WHERE id NOT IN (SELECT MAX(id) FROM results GROUP BY brand,target_date,chat_id); DROP INDEX IF EXISTS idx_scan_active_date; DROP INDEX IF EXISTS idx_result_old_unique; CREATE UNIQUE INDEX IF NOT EXISTS idx_scan_active_brand_date ON scans(brand,target_date) WHERE status IN ('QUEUED','RUNNING','PAUSED'); CREATE UNIQUE INDEX IF NOT EXISTS idx_results_brand_chat ON results(brand,target_date,chat_id); CREATE INDEX IF NOT EXISTS idx_results_scan ON results(scan_id); CREATE INDEX IF NOT EXISTS idx_results_status ON results(brand,target_date,status);`)
 }
 validBrand(b){b=String(b||'').trim().toUpperCase();return BRANDS.includes(b)?b:null}
 audit(a,x,d=''){this.db.prepare('INSERT INTO audit(ts,actor,action,detail) VALUES(?,?,?,?)').run(nowIso(),a,x,String(d).slice(0,4000))}
 settingGet(k){return this.db.prepare('SELECT v FROM settings WHERE k=?').get(k)?.v??null} settingSet(k,v){this.db.prepare(`INSERT INTO settings(k,v,updated_at) VALUES(?,?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v,updated_at=excluded.updated_at`).run(k,String(v??''),nowIso())}
 settingsPublic(){return{auto_scan_time:this.settingGet('auto_scan_time')||process.env.AUTO_SCAN_TIME||'',telegram_enabled:(this.settingGet('telegram_enabled')??'1')==='1'}} telegramToken(){return this.settingGet('telegram_bot_token')||process.env.TELEGRAM_BOT_TOKEN||''}
 brandChatId(b){return this.settingGet(`telegram_chat_id:${b}`)||''} setBrandChatId(b,v){this.settingSet(`telegram_chat_id:${b}`,v)} brands(){return BRANDS.map(name=>({name,telegram_chat_id:this.brandChatId(name)}))}
 upsertDevice({id,name,version,error,currentJob}){const n=nowIso();this.db.prepare(`INSERT INTO devices(id,name,version,online,last_seen,last_error,current_job_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,version=excluded.version,online=1,last_seen=excluded.last_seen,last_error=excluded.last_error,current_job_id=excluded.current_job_id,updated_at=excluded.updated_at`).run(id,name||id,version||'',1,n,error||null,currentJob||null,n,n)}
 markOfflineStale(sec=45){this.db.prepare('UPDATE devices SET online=0 WHERE last_seen<?').run(new Date(Date.now()-sec*1000).toISOString())} devices(){this.markOfflineStale();return this.db.prepare('SELECT * FROM devices ORDER BY online DESC,last_seen DESC').all()}
 createScan(brand,date,actor='admin'){brand=this.validBrand(brand);if(!brand)throw new Error('INVALID_BRAND');let s=this.db.prepare("SELECT * FROM scans WHERE brand=? AND target_date=? AND status IN ('QUEUED','RUNNING','PAUSED') ORDER BY created_at DESC LIMIT 1").get(brand,date);if(s){if(s.status==='PAUSED'){this.db.prepare("UPDATE scans SET status='QUEUED',device_id=NULL,lock_until=NULL,error=NULL WHERE id=?").run(s.id);s=this.scan(s.id)}return{scan:s,existed:true}}const sid=id('scan'),n=nowIso();this.db.prepare('INSERT INTO scans(id,brand,target_date,status,created_at) VALUES(?,?,?,?,?)').run(sid,brand,date,'QUEUED',n);this.audit(actor,'SCAN_CREATED',`${brand} ${date} ${sid}`);return{scan:this.scan(sid),existed:false}}
 scan(sid){return this.db.prepare('SELECT * FROM scans WHERE id=?').get(sid)} scans(limit=100){return this.db.prepare('SELECT * FROM scans ORDER BY created_at DESC LIMIT ?').all(Math.min(+limit||100,500))}
 claimScan(deviceId,brand){brand=this.validBrand(brand);if(!brand)return null;this.db.exec('BEGIN IMMEDIATE;');try{const n=nowIso();this.db.prepare("UPDATE scans SET status='QUEUED',device_id=NULL,lock_until=NULL WHERE status='RUNNING' AND lock_until<?").run(n);const s=this.db.prepare("SELECT * FROM scans WHERE brand=? AND status='QUEUED' ORDER BY created_at ASC LIMIT 1").get(brand);if(!s){this.db.exec('COMMIT;');return null}this.db.prepare("UPDATE scans SET status='RUNNING',device_id=?,started_at=COALESCE(started_at,?),lock_until=? WHERE id=? AND status='QUEUED'").run(deviceId,n,new Date(Date.now()+60000).toISOString(),s.id);const out=this.scan(s.id);this.db.exec('COMMIT;');return out}catch(e){try{this.db.exec('ROLLBACK;')}catch{}throw e}}
 heartbeatScan(sid,d,p={}){const s=this.scan(sid);if(!s||s.device_id!==d||s.status!=='RUNNING')return false;this.db.prepare(`UPDATE scans SET lock_until=?,total=MAX(total,?),checked=MAX(checked,?),normal=MAX(normal,?),mischat=MAX(mischat,?),errors=MAX(errors,?) WHERE id=?`).run(new Date(Date.now()+60000).toISOString(),p.total||0,p.checked||0,p.normal||0,p.mischat||0,p.errors||0,sid);return true}
 hasResult(brand,date,chatId,scannerVersion=''){const r=this.db.prepare('SELECT scanner_version,status FROM results WHERE brand=? AND target_date=? AND chat_id=?').get(brand,date,chatId);if(!r)return false;if(!['NORMAL','MISCHAT'].includes(String(r.status||'')))return false;return String(r.scanner_version||'')===String(scannerVersion||'')}
 saveScreenshot(brand,chatId,data){if(!data)return null;const m=/^data:image\/(png|jpeg);base64,(.+)$/s.exec(data);if(!m)return null;const dir=path.join(this.shotDir,brand.replace(/[^A-Z0-9_-]/g,'_'));fs.mkdirSync(dir,{recursive:true});const name=`${brand.replace(/[^A-Z0-9_-]/g,'_')}/${Date.now()}-${String(chatId).replace(/[^a-zA-Z0-9_-]/g,'_')}.${m[1]==='jpeg'?'jpg':'png'}`;fs.writeFileSync(path.join(this.shotDir,name),Buffer.from(m[2],'base64'));return name}
 upsertResult(r){const n=nowIso(),v=k=>r[k]==null?'':String(r[k]),old=this.db.prepare('SELECT screenshot_path,status FROM results WHERE brand=? AND target_date=? AND chat_id=?').get(v('brand'),v('target_date'),v('chat_id'));const shot=r.screenshot_path==null?null:String(r.screenshot_path);this.db.prepare(`INSERT INTO results(scan_id,brand,target_date,chat_id,fingerprint,user_id,agent,last_customer_text,last_customer_at,status,archive_url,screenshot_path,scanner_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(brand,target_date,chat_id) DO UPDATE SET scan_id=excluded.scan_id,fingerprint=excluded.fingerprint,user_id=excluded.user_id,agent=excluded.agent,last_customer_text=excluded.last_customer_text,last_customer_at=excluded.last_customer_at,status=excluded.status,archive_url=excluded.archive_url,screenshot_path=CASE WHEN excluded.status='MISCHAT' THEN COALESCE(excluded.screenshot_path,results.screenshot_path) ELSE NULL END,scanner_version=excluded.scanner_version,telegram_status=CASE WHEN excluded.status='MISCHAT' THEN CASE WHEN results.status='MISCHAT' THEN results.telegram_status ELSE 'NOT_SENT' END ELSE 'NOT_SENT' END,telegram_error=NULL,updated_at=excluded.updated_at`).run(v('scan_id'),v('brand'),v('target_date'),v('chat_id'),v('fingerprint'),v('user_id'),v('agent'),v('last_customer_text'),v('last_customer_at'),v('status'),v('archive_url'),shot,v('scanner_version'),n,n);if(old?.screenshot_path&&v('status')!=='MISCHAT'){try{fs.unlinkSync(path.join(this.shotDir,old.screenshot_path))}catch{}}return this.db.prepare('SELECT * FROM results WHERE brand=? AND target_date=? AND chat_id=?').get(v('brand'),v('target_date'),v('chat_id'))}
 checkpoint(sid,chatId){this.db.prepare('UPDATE scans SET checkpoint_chat_id=?,checkpoint_at=? WHERE id=?').run(chatId,nowIso(),sid)}
 results(f={}){const w=[],a=[];for(const [k,col] of [['brand','brand'],['date','target_date'],['status','status'],['agent','agent']])if(f[k]){w.push(`${col}=?`);a.push(f[k])}return this.db.prepare(`SELECT * FROM results ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY created_at DESC LIMIT ?`).all(...a,Math.min(+f.limit||500,2000))}
 recountScan(sid){const rows=this.db.prepare('SELECT status,COUNT(*) c FROM results WHERE scan_id=? GROUP BY status').all(sid),c={NORMAL:0,MISCHAT:0,ERROR:0};rows.forEach(x=>c[x.status]=+x.c);this.db.prepare('UPDATE scans SET checked=?,normal=?,mischat=?,errors=? WHERE id=?').run(rows.reduce((n,x)=>n+(+x.c),0),c.NORMAL,c.MISCHAT,c.ERROR,sid);return this.scan(sid)}
 pauseScan(sid,d){const s=this.scan(sid);if(!s||s.device_id!==d)return null;this.db.prepare("UPDATE scans SET status='PAUSED',device_id=NULL,lock_until=NULL WHERE id=?").run(sid);return this.recountScan(sid)}
 completeScan(sid,d,total,error=null){const s=this.scan(sid);if(!s||s.device_id!==d)return null;this.db.prepare('UPDATE scans SET status=?,total=MAX(total,?),completed_at=?,lock_until=NULL,error=? WHERE id=?').run(error?'FAILED':'COMPLETED',total||0,nowIso(),error,sid);return this.recountScan(sid)}
 pendingTelegram(limit=20){return this.db.prepare("SELECT * FROM results WHERE status='MISCHAT' AND telegram_status IN ('NOT_SENT','RETRY') ORDER BY created_at ASC LIMIT ?").all(Math.min(+limit||20,100))} setTelegram(id,s,e=null){this.db.prepare('UPDATE results SET telegram_status=?,telegram_error=?,updated_at=? WHERE id=?').run(s,e,nowIso(),id)}
 dashboardSummary(brand=''){this.markOfflineStale();const y=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-86400000));const latest=brand?this.db.prepare('SELECT * FROM scans WHERE brand=? ORDER BY created_at DESC LIMIT 1').get(brand):this.db.prepare('SELECT * FROM scans ORDER BY created_at DESC LIMIT 1').get();const byAgent=brand?this.db.prepare("SELECT COALESCE(agent,'Unknown') agent,COUNT(*) count FROM results WHERE brand=? AND target_date=? AND status='MISCHAT' GROUP BY agent ORDER BY count DESC").all(brand,y):[];return{yesterday:y,latest:latest||null,devices:this.devices(),byAgent:byAgent.map(x=>({...x,count:+x.count})),brands:this.brands()}}
 close(){try{this.db.close()}catch{}}
}
module.exports={Store,BRANDS};
